site_name: 'GBIF Data pipelines'

repo_name: gbif/pipelines
repo_url: https://github.com/gbif/pipelines
edit_uri: ""

nav:
  - Home:
    - About: index.md
    - Architecture: architecture.md
    - Roadmap: roadmap.md
    - Download: download.md
    - Release notes: release-notes.md
    - License: https://www.apache.org/licenses/LICENSE-2.0
  - Ingress:
    - Overview: ingress/index.md
    - Input formats: ingress/input-formats.md
    - Identifiers: ingress/identifiers.md
    - Basic parsing: ingress/basic-parsing.md
    - Controlled vocabularies: ingress/controlled-vocabularies.md
    - Taxonomy: ingress/taxonomy.md
    - Date/Time: ingress/date-time.md
    - Location: ingress/location.md
    - Fitness for use: ingress/fitness-for-use.md
    - Invasive species: ingress/invasive-species.md
    - Traits: ingress/traits.md
    - Multimedia: ingress/multimedia.md
    - Sequences: ingress/sequences.md
    - Outlier detection: ingress/outlier-detection.md
    - Data quality flags: ingress/data-quality-flags.md
  - Indexing:
    - Overview: indexing/index.md
    - Elasticsearch: indexing/elastic-search.md
    - Solr: indexing/solr.md
  - Egress:
    - Overview: egress/index.md
    - Field delimited formats: egress/field-delimited-formats.md
    - Data packages (DwC-A): egress/data-packages.md
    - Geospatial formats: egress/geospatial-formats.md
    - Essential biodiversity variables (EBVs): egress/ebvs.md
    - Adhoc SQL: egress/sql.md
  - Community:
    - Overview: community/index.md
    - Tutorials: community/tutorials.md
    - Contributor guide: community/contributor-guide.md
    - Build and Releasing: community/build-release.md
    - People: community/people.md

theme:
  name: 'material'
  logo: 'images/GBIF-2015-mark.svg'
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  feature:
    tabs: true

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true