site_name: 'GBIF Data pipelines'

repo_name: gbif/pipelines
repo_url: https://github.com/gbif/pipelines
edit_uri: ""

nav:
  - Home:
    - About: index.md
    - Architecture: architecture.md
    - Roadmap: roadmap.md
    - Download: download.md
    - Release notes: release-notes.md
    - License: https://www.apache.org/licenses/LICENSE-2.0
  - Preparation:
    - Overview: preparation/index.md
    - Input formats: preparation/input-formats.md
    - Identifiers: preparation/identifiers.md
    - Basic parsing: preparation/basic-parsing.md
    - Controlled vocabularies: preparation/controlled-vocabularies.md
    - Taxonomy: preparation/taxonomy.md
    - Date/Time: preparation/date-time.md
    - Location: preparation/location.md
    - Fitness for use: preparation/fitness-for-use.md
    - Invasive species: preparation/invasive-species.md
    - Traits: preparation/traits.md
    - Multimedia: preparation/multimedia.md
    - Sequences: preparation/sequences.md
    - Outlier detection: preparation/outlier-detection.md
    - Data quality flags: preparation/data-quality-flags.md
  - Indexing:
    - Overview: indexing/index.md
    - Elasticsearch: indexing/elastic-search.md
    - Solr: indexing/solr.md
  - Formats:
    - Overview: formats/index.md
    - Field delimited formats: formats/field-delimited-formats.md
    - Data packages (DwC-A): formats/data-packages.md
    - Geospatial formats: formats/geospatial-formats.md
    - Essential biodiversity variables (EBVs): formats/ebvs.md
    - Adhoc SQL: formats/sql.md
  - Community:
    - Overview: community/index.md
    - Tutorials: community/tutorials.md
    - Contributor guide: community/contributor-guide.md
    - Build and Releasing: community/build-release.md
    - People: community/people.md

theme:
  name: 'material'
  logo: 'images/GBIF-2015-mark.svg'
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  feature:
    tabs: true

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.details
  - toc:
      permalink: true